services:
  app:
    container_name: appkit-dev
    image: appkit/ui-dev
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: 3.13-bookworm
    volumes:
      - ../..:/workspaces:rw,cached
    command: sleep infinity
    networks:
      - appkit-network

  db:
    container_name: appkit-db
    image: pgvector/pgvector:pg15
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: appkit-db
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
    networks:
      - appkit-network

volumes:
  postgres-data:
    name: appkit-postgres-data

networks:
  appkit-network:
    driver: bridge
